name: Scan with KICS and upload SARIF

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-github-action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkmarx AST Github Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: ${{secrets.CX_TENANT}}
          cx_client_id: ${{secrets.CX_CLIENT_ID}}
          cx_client_secret: ${{secrets.CX_CLIENT_SECRET}}
          branch: ${{ github.ref }}
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: 'terraform'
          # when provided with a directory on output_path
          # it will generate the specified reports file named 'results.{extension}'
          # in this example it will generate:
          # - results-dir/results.json
          # - results-dir/results.sarif
          output_path: results-dir
          platform_type: terraform
          output_formats: 'json,sarif'
          exclude_paths: "terraform/gcp/big_data.tf,terraform/azure"
          # seek query id in it's metadata.json
          exclude_queries: 0437633b-daa6-4bbc-8526-c0d2443b946e
      - name: Show results
        run: |
          cat results-dir/results.sarif
          cat results-dir/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@latest
        with:
          sarif_file: results-dir/results.sarif
